// Build-time extraction of FontAwesome path data into static SVG React components.
// Output: src/components/icons.generated.tsx. FontAwesome is a devDependency only.
import { writeFileSync } from 'node:fs';
import * as brands from '@fortawesome/free-brands-svg-icons';
import * as solid from '@fortawesome/free-solid-svg-icons';
import * as regular from '@fortawesome/free-regular-svg-icons';

const wanted = {
  unity: brands.faUnity, salesforce: brands.faSalesforce, angular: brands.faAngular,
  html: brands.faHtml5, css: brands.faCss3, javascript: brands.faJs, nodejs: brands.faNode,
  react: brands.faReact, linkedin: brands.faLinkedin, github: brands.faGithub,
  envelope: regular.faEnvelope, chevronLeft: solid.faChevronLeft, chevronRight: solid.faChevronRight,
};

let out = `// GENERATED by scripts/gen-icons.mjs — do not edit.\nimport type { SVGProps } from 'react';\ntype P = SVGProps<SVGSVGElement>;\n`;
for (const [name, icon] of Object.entries(wanted)) {
  const [w, h, , , path] = icon.icon;
  const d = Array.isArray(path) ? path.join(' ') : path;
  out += `export const Fa_${name} = (p: P) => (<svg viewBox="0 0 ${w} ${h}" fill="currentColor" aria-hidden="true" {...p}><path d="${d}" /></svg>);\n`;
}
writeFileSync(new URL('../src/components/icons.generated.tsx', import.meta.url), out);
console.log('wrote', Object.keys(wanted).length, 'icons');
