// Build-time extraction of FontAwesome path data into a static artwork record.
// Output: src/components/icons.generated.tsx. FontAwesome is a devDependency only,
// so nothing from @fortawesome ever reaches the client bundle.
import { writeFileSync } from 'node:fs';
import * as brands from '@fortawesome/free-brands-svg-icons';
import * as regular from '@fortawesome/free-regular-svg-icons';
import * as solid from '@fortawesome/free-solid-svg-icons';

// Keys are icon ids: the `icon` field of the skill registry, plus contact and toolbar icons.
const WANTED = {
  unity: brands.faUnity,
  salesforce: brands.faSalesforce,
  angular: brands.faAngular,
  html5: brands.faHtml5,
  css3: brands.faCss3,
  js: brands.faJs,
  node: brands.faNode,
  react: brands.faReact,
  linkedin: brands.faLinkedin,
  github: brands.faGithub,
  envelope: regular.faEnvelope,
  'chevron-left': solid.faChevronLeft,
  'chevron-right': solid.faChevronRight,
};

/** Bare identifier where possible, quoted otherwise. */
const objectKey = (id) => (/^[a-z][a-zA-Z0-9]*$/.test(id) ? id : `'${id}'`);

let out = `// GENERATED by scripts/gen-icons.mjs — do not edit. Run \`pnpm gen:icons\`.
import type { IconArtwork } from './icons';

export const GENERATED_ICONS = {
`;
for (const [id, icon] of Object.entries(WANTED)) {
  const [width, height, , , path] = icon.icon;
  const d = Array.isArray(path) ? path.join(' ') : path;
  out += `  ${objectKey(id)}: {
    viewBox: '0 0 ${width} ${height}',
    children: <path d="${d}" />,
  },
`;
}
out += `} satisfies Record<string, IconArtwork>;
`;

writeFileSync(new URL('../src/components/icons.generated.tsx', import.meta.url), out);
console.log(`wrote ${Object.keys(WANTED).length} icons to src/components/icons.generated.tsx`);
