name: prod
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: create env file
        run: |
          touch .env.prod
          echo API_URL=${{ vars.API_URL }} >> .env.prod
          echo PRODUCTION=${{ vars.PRODUCTION }} >> .env.prod
          echo PRERENDER_TOKEN=${{ secrets.PRERENDER_TOKEN }} >> .env.prod
          echo TURSO_TOKEN=${{ secrets.TURSO_TOKEN }} >> .env.prod
          echo TURSO_URL=${{ vars.TURSO_URL }} >> .env.prod
          echo CLERK_PUBLIC_KEY=${{ vars.CLERK_PUBLIC_KEY }} >> .env.prod
          echo CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }} >> .env.prod
      - name: create environment directory
        run: |
          mkdir src/environments
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
