name: prod
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
        env:
            ENVIRONMENT_DETAILS: '${{ secrets.ENVIRONMENT_DETAILS }}'
      - name: create env file
        run: |
          touch .env.prod
          echo API_URL=${{ secrets.API_URL }} >> .env.prod
          echo PRODUCTION=${{ secrets.PRODUCTION }} >> .env.prod
          echo PRERENDER_TOKEN=${{ secrets.PRERENDER_TOKEN }} >> .env.prod
          echo TURSO_TOKEN=${{ secrets.TURSO_TOKEN }} >> .env.prod
          echo TURSO_URL=${{ secrets.TURSO_URL }} >> .env.prod
      - name: create environment directory
        run: |
          mkdir src/environments
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
