name: staging
on:
  push:
    branches:
      - staging
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: create env file
        run: |
          touch .env.staging
          echo API_URL=${{ vars.API_URL }} >> .env.staging
          echo PRODUCTION=${{ vars.PRODUCTION }} >> .env.staging
          echo TURSO_TOKEN=${{ secrets.TURSO_TOKEN }} >> .env.staging
          echo TURSO_URL=${{ vars.TURSO_URL }} >> .env.staging
      - name: create environment directory
        run: |
          mkdir src/environments
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
